### ISSUE TITLE
Unable to execute test cases in parallel

### ISSUE THREAD

**Issue by Zarmeena** [browserstack/cucumber-js-browserstack#20]
While trying to execute the test cases in parallel mode using 'npm run parallel' command , we are getting the following error:

   **throw er; // Unhandled 'error' event
      ^
Error: spawn /usr/bin/env ENOENT
    at _errnoException (util.js:1003:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at process._tickCallback (internal/process/next_tick.js:152:19)
    at Function.Module.runMain (module.js:703:11)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cucumber-js-browserstack@0.1.0 parallel: `cross-env CONFIG_FILE=parallel ./scripts/cucumber-runner.js features/single.feature`
npm ERR! Exit status 1**

Do we need to set any environment variable to execute the test case using the provided command?

**Comment by RohanImmanuel** [comment]
Hi @Zarmeena you would be required to eighter

1. Update your username and access key in the *.conf.js files in the /conf directory

**OR**

2. Set the environment variables BROWSERSTACK_USERNAME and BROWSERSTACK_ACCESS_KEY
<br>
Addatiollay, I was unable to reproduce the above error. This may be related to your environment. Could you please share more details regarding the same.
