### ISSUE TITLE
Issue while running code in parallel configuration

### ISSUE THREAD

**Issue by rahulsingh3005** [browserstack/cucumber-js-browserstack#21]
Hi Team,

Tried running code for parallel config. Below is the error stack I am getting on console. Need help. Am I missing out some configuration?

c:\Users\rsingh\cucumber-js-browserstack-master>npm run parallel

> cucumber-js-browserstack@0.1.0 parallel c:\Users\rsingh\cucumber-js-browserstack-master
> cross-env CONFIG_FILE=parallel ./scripts/cucumber-runner.js features/single.feature

events.js:298
      throw er; // Unhandled 'error' event
      ^

Error: spawn /usr/bin/env ENOENT
←[90m    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)←[39m
←[90m    at onErrorNT (internal/child_process.js:467:16)←[39m
←[90m    at processTicksAndRejections (internal/process/task_queues.js:84:21)←[39m
Emitted 'error' event on ChildProcess instance at:
←[90m    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)←[39m
←[90m    at onErrorNT (internal/child_process.js:467:16)←[39m
←[90m    at processTicksAndRejections (internal/process/task_queues.js:84:21)←[39m {
  errno: ←[33m-4058←[39m,
  code: ←[32m'ENOENT'←[39m,
  syscall: ←[32m'spawn /usr/bin/env'←[39m,
  path: ←[32m'/usr/bin/env'←[39m,
  spawnargs: [
    ←[32m'node'←[39m,
    ←[32m'./node_modules/.bin/cucumber-js'←[39m,
    ←[32m'features/single.feature'←[39m
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cucumber-js-browserstack@0.1.0 parallel: `cross-env CONFIG_FILE=parallel ./scripts/cucumber-runner.js features/single.feature`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cucumber-js-browserstack@0.1.0 parallel script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     \\servfs\RDSFolderRedirection$\rsingh\Application Data\npm-cache\_logs\2020-03-12T09_52_33_612Z-debug.log

**Comment by shawnlobo96** [comment]
Hey @rahulsingh3005 have you added your Browserstack username and access key in your environment variables or declared the same in your config file?

If not, you can either:

1. Update your username and access key in the `*.conf.js` files in the /conf directory

OR

2. Set the environment variables `BROWSERSTACK_USERNAME` and `BROWSERSTACK_ACCESS_KEY`

The error seems to be related to your environment config. 

Can you share more details regarding the same?

**Comment by rahulsingh3005** [comment]
Hi @shawnlobo96 thanks for responding.
I have updated username password and server details in parallel.conf.js files in /conf directory.
I am able to run single but when I try to run for parallel I get above error. 
I am using Windows 10 , Node v13.7.0 , npm v6.13.6.
Please let me know what additional details you need so that I can share.

**Comment by rahulsingh3005** [comment]
> Hey @rahulsingh3005 have you added your Browserstack username and access key in your environment variables or declared the same in your config file?
> 
> If not, you can either:
> 
> 1. Update your username and access key in the `*.conf.js` files in the /conf directory
> 
> OR
> 
> 1. Set the environment variables `BROWSERSTACK_USERNAME` and `BROWSERSTACK_ACCESS_KEY`
> 
> The error seems to be related to your environment config.
> 
> Can you share more details regarding the same?

**Comment by rahulsingh3005** [comment]
> Hey @rahulsingh3005 have you added your Browserstack username and access key in your environment variables or declared the same in your config file?
> 
> If not, you can either:
> 
> 1. Update your username and access key in the `*.conf.js` files in the /conf directory
> 
> OR
> 
> 1. Set the environment variables `BROWSERSTACK_USERNAME` and `BROWSERSTACK_ACCESS_KEY`
> 
> The error seems to be related to your environment config.
> 
> Can you share more details regarding the same?

Hi @shawnlobo96 thanks for responding.
I have updated username password and server details in parallel.conf.js files in /conf directory.
I am able to run single but when I try to run for parallel I get above error.
I am using Windows 10 , Node v13.7.0 , npm v6.13.6.
Please let me know what additional details you need so that I can share.

**Comment by rahulsingh3005** [comment]
> > Hey @rahulsingh3005 have you added your Browserstack username and access key in your environment variables or declared the same in your config file?
> > If not, you can either:
> > 
> > 1. Update your username and access key in the `*.conf.js` files in the /conf directory
> > 
> > OR
> > 
> > 1. Set the environment variables `BROWSERSTACK_USERNAME` and `BROWSERSTACK_ACCESS_KEY`
> > 
> > The error seems to be related to your environment config.
> > Can you share more details regarding the same?

Hi @shawnlobo96 thanks for responding.
I have updated username password and server details in parallel.conf.js files in /conf directory.
I am able to run single but when I try to run for parallel I get above error.
I am using Windows Server 2008 R2 , Node v13.7.0 , npm v6.13.6.
Please let me know what additional details you need so that I can share.

**Comment by rahulsingh3005** [comment]
> @shawnlobo96

Hi @shawnlobo96  do we have any update?

**Comment by RohanImmanuel** [comment]
@rahulsingh3005 I couldn't replicate this error on a windows machine using the config shared, can you share any additional changes made to the repo aside form the credentials

**Comment by rahulsingh3005** [comment]
> @rahulsingh3005 I couldn't replicate this error on a windows machine using the config shared, can you share any additional changes made to the repo aside form the credentials

Hi @RohanImmanuel I have not made any change apart from the credentials. 
I have  Node v13.7.0 , npm v6.13.6.

**Comment by RohanImmanuel** [comment]
@rahulsingh3005 a screen share session can help us debug this better
you can reach out to support@browserstack.com to schedule the same

**Comment by RohanImmanuel** [comment]
@rahulsingh3005 could check if the linked fork resolves your issue
https://github.com/RohanImmanuel/cucumber-js-browserstack

PR: https://github.com/browserstack/cucumber-js-browserstack/pull/22
